"""initial schema

Revision ID: 4b01ce76efcd
Revises: 
Create Date: 2026-08-20 23:23:47.269667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b01ce76efcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('locale', sa.String(length=12), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('mrr_cents', sa.Integer(), nullable=False),
    sa.Column('tenure_days', sa.Integer(), nullable=False),
    sa.Column('lifetime_recovered_cents', sa.Integer(), nullable=False),
    sa.Column('lifetime_failed_count', sa.Integer(), nullable=False),
    sa.Column('lifetime_recovered_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=False)
    op.create_table('playbooks',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('failure_class', sa.String(length=32), nullable=False),
    sa.Column('retry_offsets_hours', sa.JSON(), nullable=False),
    sa.Column('channel_ladder', sa.JSON(), nullable=False),
    sa.Column('offer_policy', sa.String(length=200), nullable=True),
    sa.Column('cases_closed', sa.Integer(), nullable=False),
    sa.Column('cases_recovered', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_playbooks_failure_class'), 'playbooks', ['failure_class'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('customer_id', sa.String(length=40), nullable=False),
    sa.Column('plan_name', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('interval', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_billing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_customer_id'), 'subscriptions', ['customer_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_external_id'), 'subscriptions', ['external_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=True),
    sa.Column('subscription_id', sa.String(length=40), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_external_id'), 'invoices', ['external_id'], unique=False)
    op.create_index('ix_invoices_status_due', 'invoices', ['status', 'due_at'], unique=False)
    op.create_index(op.f('ix_invoices_subscription_id'), 'invoices', ['subscription_id'], unique=False)
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('invoice_id', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=24), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=120), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.String(length=400), nullable=True),
    sa.Column('failure_class', sa.String(length=32), nullable=False),
    sa.Column('triage_rationale', sa.String(length=500), nullable=True),
    sa.Column('recovery_score', sa.Float(), nullable=True),
    sa.Column('score_confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('amount_at_risk_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('strategy', sa.JSON(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cases_status_class', 'recovery_cases', ['status', 'failure_class'], unique=False)
    op.create_index(op.f('ix_recovery_cases_failure_class'), 'recovery_cases', ['failure_class'], unique=False)
    op.create_index(op.f('ix_recovery_cases_invoice_id'), 'recovery_cases', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_provider_payment_id'), 'recovery_cases', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_recovery_cases_status'), 'recovery_cases', ['status'], unique=False)
    op.create_table('agent_steps',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('thread_id', sa.String(length=40), nullable=False),
    sa.Column('node', sa.String(length=40), nullable=False),
    sa.Column('input', sa.JSON(), nullable=True),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('reasoning', sa.String(length=1000), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_steps_case_id'), 'agent_steps', ['case_id'], unique=False)
    op.create_index(op.f('ix_agent_steps_thread_id'), 'agent_steps', ['thread_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.String(length=4000), nullable=False),
    sa.Column('generated_by', sa.String(length=40), nullable=False),
    sa.Column('guardrail_flags', sa.JSON(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=120), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_table('recovery_attempts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('case_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('notes', sa.String(length=400), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['recovery_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recovery_attempts_case_id'), 'recovery_attempts', ['case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_attempts_case_id'), table_name='recovery_attempts')
    op.drop_table('recovery_attempts')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_agent_steps_thread_id'), table_name='agent_steps')
    op.drop_index(op.f('ix_agent_steps_case_id'), table_name='agent_steps')
    op.drop_table('agent_steps')
    op.drop_index(op.f('ix_recovery_cases_status'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_provider_payment_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_invoice_id'), table_name='recovery_cases')
    op.drop_index(op.f('ix_recovery_cases_failure_class'), table_name='recovery_cases')
    op.drop_index('ix_cases_status_class', table_name='recovery_cases')
    op.drop_table('recovery_cases')
    op.drop_index(op.f('ix_invoices_subscription_id'), table_name='invoices')
    op.drop_index('ix_invoices_status_due', table_name='invoices')
    op.drop_index(op.f('ix_invoices_external_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_subscriptions_external_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_customer_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_playbooks_failure_class'), table_name='playbooks')
    op.drop_table('playbooks')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
